### ISSUE TITLE
Timeline for Firefox VideoEncoder support

### ISSUE THREAD

**Issue by benz2012** [Vanilagy/webm-muxer#20]
This is a question somewhat unrelated to this library, but:

I know most browsers have a public ticket system that allows devs to track the progress of features being added/fixed. I looked everywhere yesterday and couldn't find any mention of a timeline for [VideoEncoder support in Firefox](https://developer.mozilla.org/en-US/docs/Web/API/VideoEncoder#browser_compatibility), like if it was even on their radar or not.

Do you know where to look for this? Are you in any secret discords where they talk about it?

Love your library by the way, was a breeze to implement & use, with no headaches yet.

**Comment by Vanilagy** [comment]
It's funny you say this, because I feel _exactly_ the same way. I was like, yeah for sure there's gonna be some thread about this, either some Reddit post or some Firefox internal discussion about WebCodecs support. But I also found absolutely nothing, as if they just won't ever consider adding it ever.

So yeah, I'm as lost as you are on this. Would be a shame if they don't feel the need to implement it at all. I'm sure it's a good amount of work, but Firefox is already packed with the codecs themselves, so "all it would take" is some wiring up. There is [this](https://github.com/mozilla/standards-positions/issues/209), but I think it's just them saying "Yup, I think it's a good API". Besides that, nothing.

I think you'll need to resort to telling people to use Chromium or heck, even Safari. Hate doing that personally too, but what else can you do here.

And thank you for the nice words!

**Comment by HighCommander4** [comment]
This mailing list post seems relevant: https://groups.google.com/a/mozilla.org/g/dev-platform/c/3g0fnn6682A

**Comment by Vanilagy** [comment]
Huge news!

**Comment by dezmou** [comment]
Look like VideoDecoder does not return undefined in Firefox Nightly anymore.
