### ISSUE TITLE
Are there plans to support demux webm file？

### ISSUE THREAD

**Issue by hughfenghen** [Vanilagy/webm-muxer#22]
Hi there, can webm files be demuxed into chunked data, which then can be fed into VideoDecoder?

**Comment by Vanilagy** [comment]
There are no plans to add demuxing support, this library is solely for muxing. Demuxing is a whole different beast since you have to properly support all the files out there in the wild. But yes, the JS world definitely needs explicit demuxing functionality too, going beyond regular playback.

[This library](https://github.com/jscodec/jswebm) looks proper and the demo seems legit, but it doesn't seem to be too well documented. If you need something really primitive you might be able to `captureStream` on a video element and then pipe that into a MediaStreamTrackProcessor to get the frames, but that's quite a limiting approach, I agree.
