### ISSUE TITLE
Stream to web storage

### ISSUE THREAD

**Issue by nsharma1396** [Vanilagy/webm-muxer#34]
Hi @Vanilagy 

Just wanted to check if there is any way that we can use the streaming option to stream data to web storage like IndexedDB.
I would like to avoid array buffer target as the in-memory usage may increase for larger videos but I do not have the flexibility to prompt for saving to a file hence was wondering if an in-memory streaming option is available somehow

Thanks,
Neeraj

**Comment by Vanilagy** [comment]
You can't really "stream" to IndexedDB sadly, which is the problem here. Of course, we could chunk it up and write multiple ArrayBuffers into IndexedDB, but reading the file and playing it back is the issue then in that case. If we had an entire Blob storing the media in the IndexedDB, that would solve the problem (because the browser intelligently reads from the Blob), but to write the Blob we need to have the entire video in memory, so that's no option here.

I suggest you look into using the [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system)! This _will_ solve your problem and does _not_ require you to ask for user permission, and you can use it to store large files you can incrementally write to.

**Comment by nsharma1396** [comment]
Awesome! Thanks, will take a look into it 👍
