### ISSUE TITLE
AAC already supported?

### ISSUE THREAD

**Issue by rafael2k** [Vanilagy/webm-muxer#4]
I wonder if I get a selected chrome with AAC support already in place, can mux it to a mkv?

Using codecid: "A_AAC/MPEG4/LC"

https://matroska.org/technical/codec_specs.html

**Comment by Vanilagy** [comment]
Yea should work. Not valid by the strict WebM spec, but probably still plays back correctly in many players. I didn't try AAC but I tried H.264 video and that stuff worked like a charm too.

**Comment by rafael2k** [comment]
Thanks! Reading Matroska spec, it seems I need:
    The docType of the EBML Header MUST be “matroska”.
    The EBMLMaxIDLength of the EBML Header MUST be “4”.
    The EBMLMaxSizeLength of the EBML Header MUST be between “1” and “8” inclusive.

I'll try. Could this option (webm or mkv) be parametrized? 
Thanks!

**Comment by Vanilagy** [comment]
Yeah, for sure! I mean,  it's a bit weird, since this project is called `webm-muxer` but really is an MKV muxer (since WebM's a subset of MKV). Of course, adding a parameter to set MKV or not is easy to add, but I guess it would've been better to make `mkv-muxer` and give that a "WebM or not" flag instead.

However, I don't wanna rename this project now. Dunno. Weird stuff. Guess WebM is more well-known in the web community anyway, so it should be fine!

**Comment by rafael2k** [comment]
Hey, don't bother about the project name. Webm-muxer it is, and WebM muxing should stay as default forever, as this is what people will want, for 99.9%. It is just a bonus having mkv muxing (and support for all WebCodecs muxing, including AAC!)
: )

**Comment by Vanilagy** [comment]
Here you go :)

**Comment by rafael2k** [comment]
Yay! tks!
: )
